# Customer purchase Project

In [2]:
import pandas as pd

# Create customer data
data = {
    "CustomerID": [1,2,3,4,5,6,7,8,9,10],
    "Name": ["Amit","Ravi","Sita","Neha","John","Sara","Raj","Priya","Karan","Anu"],
    "City": ["Delhi","Mumbai","Delhi","Pune","Bangalore","Mumbai","Chennai","Delhi","Pune","Bangalore"],
    "Age": [25,30,22,28,35,27,32,24,29,26],
    "PurchaseAmount": [200,500,150,300,700,400,250,350,450,600]
}

df = pd.DataFrame(data)

print(df)

   CustomerID   Name       City  Age  PurchaseAmount
0           1   Amit      Delhi   25             200
1           2   Ravi     Mumbai   30             500
2           3   Sita      Delhi   22             150
3           4   Neha       Pune   28             300
4           5   John  Bangalore   35             700
5           6   Sara     Mumbai   27             400
6           7    Raj    Chennai   32             250
7           8  Priya      Delhi   24             350
8           9  Karan       Pune   29             450
9          10    Anu  Bangalore   26             600

# 1. Show First 5 Rows

In [6]:
df.head()

   CustomerID  Name       City  Age  PurchaseAmount
0           1  Amit      Delhi   25             200
1           2  Ravi     Mumbai   30             500
2           3  Sita      Delhi   22             150
3           4  Neha       Pune   28             300
4           5  John  Bangalore   35             700

# 2. Filter Customers from Delhi

In [10]:
df[df["City"] == "Delhi"]

   CustomerID   Name   City  Age  PurchaseAmount
0           1   Amit  Delhi   25             200
2           3   Sita  Delhi   22             150
7           8  Priya  Delhi   24             350

# Customers with Purchase > 400

In [16]:
df[df["PurchaseAmount"] > 400]

   CustomerID   Name       City  Age  PurchaseAmount
1           2   Ravi     Mumbai   30             500
4           5   John  Bangalore   35             700
8           9  Karan       Pune   29             450
9          10    Anu  Bangalore   26             600

# 4. Average Purchase

In [20]:
df["PurchaseAmount"].mean()

np.float64(390.0)

# 6. City-wise Total Purchase

In [24]:
df.groupby("City")["PurchaseAmount"].sum()

City
Bangalore    1300
Chennai       250
Delhi         700
Mumbai        900
Pune          750
Name: PurchaseAmount, dtype: int64

# Add Discount Column (10%)

In [27]:
df["Discount"] = df["PurchaseAmount"] * 0.10

# Sort by Highest Purchase

In [28]:
df.sort_values(by = "PurchaseAmount", ascending = False)

   CustomerID   Name       City  Age  PurchaseAmount  Discount
4           5   John  Bangalore   35             700      70.0
9          10    Anu  Bangalore   26             600      60.0
1           2   Ravi     Mumbai   30             500      50.0
8           9  Karan       Pune   29             450      45.0
5           6   Sara     Mumbai   27             400      40.0
7           8  Priya      Delhi   24             350      35.0
3           4   Neha       Pune   28             300      30.0
6           7    Raj    Chennai   32             250      25.0
0           1   Amit      Delhi   25             200      20.0
2           3   Sita      Delhi   22             150      15.0

# Step 6: Export to Excel (Very Important 🔥)

In [30]:
df.to_excel("customer_data.xlsx", index=False)